

A convolutional neural network model for survival prediction based on prognosis-related cascaded Wx feature selection

https://www.laboratoryinvestigation.org/article/S0023-6837(22)00114-3/fulltext

https://github.com/wangwangCCChen/CNN-Cox

https://github.com/ucsffrancislab/CNN-Cox

In [1]:
#from Trainmodel import traindcnncoxmodel,traincnncoxmodel
#from utils import avgcindex

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1" 
import math
import numpy as np
import pandas as pd
#from model import cnncox,dcnncox,nncox
from earlystoping import MyCallback
from utils import nll,avgcindex,setup_seed
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold,train_test_split
from lifelines.utils import concordance_index
import matplotlib.pyplot as plt
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense,Dropout,Input,Flatten,concatenate
from tensorflow.keras.regularizers import l2

2024-04-18 11:54:52.962181: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


GENE_2_counts_normalized.subject_unique.metadata.all.tsv

was created from the REdiscoverTE output converted to a tsv.

The metadata came from Eduardo's initial gbm_train/gbm_test data files.

In [3]:

cancer_name='TCGA'
Cindex=[]

current_path='../data/our/'
output_path=current_path+'/GENE_2_counts_normalized.subject_unique.metadata.all.tsv'
save_path="../save model/our/my2DCNNCox/"
os.makedirs(save_path,exist_ok=True)

In [4]:

seed=42

setup_seed(seed)

df_exp=pd.read_csv(output_path,index_col=0,sep="\t",low_memory=False)

In [5]:
df_exp.head()

,sex,IDH,x1p19q,TERT,MGMT,Age,Survival_months,Vital_status,EGFR_re,CDKN2A_re,...,ENSG00000284649,ENSG00000284671,ENSG00000284680,ENSG00000284684,ENSG00000284691,ENSG00000284701,ENSG00000284723,"ENSG00000284733,ENSG00000284662",ENSG00000284741,NA
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,male,WT,non-codel,NaN,Unmethylated,78,14.718995,1,Wildtype,Deleted,...,7.766,9.993,0,0.0,47.574,0,1,0.0,0.0,569.221
02-0055,female,WT,non-codel,NaN,Unmethylated,62,2.496972,1,Amplified,Wildtype,...,10.742,0.000,0,0.0,25.980,0,0,0.0,0.0,491.114
02-2485,male,WT,non-codel,Mutant,Unmethylated,53,15.441803,0,Amplified,Wildtype,...,5.379,0.000,0,0.0,69.000,0,1,0.0,0.0,717.150
02-2486,male,WT,non-codel,NaN,Unmethylated,64,16.197466,0,Amplified,Deleted,...,2.037,4.746,0,0.0,49.948,0,0,0.0,0.0,274.183
06-0125,female,WT,non-codel,Mutant,Methylated,63,47.573895,1,Amplified,Deleted,...,8.879,4.237,0,0.0,122.020,0,1,4.0,0.0,657.634

In [6]:
df_exp.drop(columns=['IDH','x1p19q','TERT','MGMT'],inplace=True)
df_exp.head()


# EGFR_re, CDKN2A_re ?

# what is the column "NA" from?

,sex,Age,Survival_months,Vital_status,EGFR_re,CDKN2A_re,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,...,ENSG00000284649,ENSG00000284671,ENSG00000284680,ENSG00000284684,ENSG00000284691,ENSG00000284701,ENSG00000284723,"ENSG00000284733,ENSG00000284662",ENSG00000284741,NA
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,male,78,14.718995,1,Wildtype,Deleted,2350.460,1.000,633.000,439.035,...,7.766,9.993,0,0.0,47.574,0,1,0.0,0.0,569.221
02-0055,female,62,2.496972,1,Amplified,Wildtype,2893.011,825.001,2382.838,569.035,...,10.742,0.000,0,0.0,25.980,0,0,0.0,0.0,491.114
02-2485,male,53,15.441803,0,Amplified,Wildtype,4940.435,5.000,1128.869,695.463,...,5.379,0.000,0,0.0,69.000,0,1,0.0,0.0,717.150
02-2486,male,64,16.197466,0,Amplified,Deleted,4338.707,7.000,1089.000,588.688,...,2.037,4.746,0,0.0,49.948,0,0,0.0,0.0,274.183
06-0125,female,63,47.573895,1,Amplified,Deleted,3621.526,6.000,1226.225,632.096,...,8.879,4.237,0,0.0,122.020,0,1,4.0,0.0,657.634

In [7]:
#df_exp.fillna(0,inplace=True)

if 'sex' in df_exp.columns:
    df_exp['sex'].replace(to_replace={'female':0, 'male':1}, inplace=True)
if 'MGMT' in df_exp.columns:
    df_exp['MGMT'].replace(to_replace={'Unmethylated':0, 'Methylated':1}, inplace=True)
if 'EGFR_re' in df_exp.columns:
    df_exp['EGFR_re'].replace(to_replace={"Wildtype":0, "Amplified":1}, inplace=True)
if 'CDKN2A_re' in df_exp.columns:
    df_exp['CDKN2A_re'].replace(to_replace={"Wildtype":0, "Amplified":1, "Deleted":2}, inplace=True)

df_exp.head()

,sex,Age,Survival_months,Vital_status,EGFR_re,CDKN2A_re,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,...,ENSG00000284649,ENSG00000284671,ENSG00000284680,ENSG00000284684,ENSG00000284691,ENSG00000284701,ENSG00000284723,"ENSG00000284733,ENSG00000284662",ENSG00000284741,NA
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,1,78,14.718995,1,0,2,2350.460,1.000,633.000,439.035,...,7.766,9.993,0,0.0,47.574,0,1,0.0,0.0,569.221
02-0055,0,62,2.496972,1,1,0,2893.011,825.001,2382.838,569.035,...,10.742,0.000,0,0.0,25.980,0,0,0.0,0.0,491.114
02-2485,1,53,15.441803,0,1,0,4940.435,5.000,1128.869,695.463,...,5.379,0.000,0,0.0,69.000,0,1,0.0,0.0,717.150
02-2486,1,64,16.197466,0,1,2,4338.707,7.000,1089.000,588.688,...,2.037,4.746,0,0.0,49.948,0,0,0.0,0.0,274.183
06-0125,0,63,47.573895,1,1,2,3621.526,6.000,1226.225,632.096,...,8.879,4.237,0,0.0,122.020,0,1,4.0,0.0,657.634

In [8]:
gene_exp=df_exp.dropna(axis=0,subset = ["Vital_status", "Survival_months"])
E=np.array(gene_exp.pop("Vital_status"))
Y=np.array(gene_exp.pop("Survival_months"))

In [9]:
gene_exp.head()

,sex,Age,EGFR_re,CDKN2A_re,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,...,ENSG00000284649,ENSG00000284671,ENSG00000284680,ENSG00000284684,ENSG00000284691,ENSG00000284701,ENSG00000284723,"ENSG00000284733,ENSG00000284662",ENSG00000284741,NA
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,1,78,0,2,2350.460,1.000,633.000,439.035,304.000,534.288,...,7.766,9.993,0,0.0,47.574,0,1,0.0,0.0,569.221
02-0055,0,62,1,0,2893.011,825.001,2382.838,569.035,497.997,1123.424,...,10.742,0.000,0,0.0,25.980,0,0,0.0,0.0,491.114
02-2485,1,53,1,0,4940.435,5.000,1128.869,695.463,743.572,503.997,...,5.379,0.000,0,0.0,69.000,0,1,0.0,0.0,717.150
02-2486,1,64,1,2,4338.707,7.000,1089.000,588.688,276.264,827.419,...,2.037,4.746,0,0.0,49.948,0,0,0.0,0.0,274.183
06-0125,0,63,1,2,3621.526,6.000,1226.225,632.096,602.204,250.999,...,8.879,4.237,0,0.0,122.020,0,1,4.0,0.0,657.634

In [10]:
E.shape

(118,)

In [11]:
E[0:15]

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0])

In [12]:
E

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
Y.shape

(118,)

In [14]:
Y[0:15]

array([14.7189952,  2.4969724, 15.441803 , 16.1974657, 47.5738952,
       12.9448306, 11.8934738, 10.2835837,  7.1623682,  5.4210585,
       13.6019286,  1.0842117, 12.484862 ,  4.928235 ,  9.2650818])

In [15]:
len(gene_exp.columns)

55666

In [16]:
math.ceil(len(gene_exp.columns)**0.5)

236

In [17]:
math.ceil(len(gene_exp.columns)**0.5)**2

55696


Add a number of columns to make the dataframe column count a square ( 236 x 236 = 55696 )

In [18]:
#for i in range(55696-len(gene_exp.columns)):
#    print("extra"+str(i), end=", ")
#    col=str("extra"+str(i))
#    gene_exp["extra"+str(i)]=0

extra=["extra"+str(i) for i in range( (math.ceil(len(gene_exp.columns)**0.5)**2) - len(gene_exp.columns) )]
#gene_exp[extra]=0

gene_exp=pd.concat([gene_exp, pd.DataFrame(columns = extra)]).fillna(0)

#gene_exp.assign(extra=0)
#gene_exp.insert(2, "expenditure", 4500, allow_duplicates=False)

In [19]:
gene_exp.columns

Index(['sex', 'Age', 'EGFR_re', 'CDKN2A_re', 'ENSG00000000003',
       'ENSG00000000005', 'ENSG00000000419', 'ENSG00000000457',
       'ENSG00000000460', 'ENSG00000000938',
       ...
       'extra20', 'extra21', 'extra22', 'extra23', 'extra24', 'extra25',
       'extra26', 'extra27', 'extra28', 'extra29'],
      dtype='object', length=55696)

In [20]:
len(gene_exp.columns)

55696

In [21]:
X=np.array(gene_exp)

In [22]:
X.shape

(118, 55696)

In [23]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [24]:
X=X.astype('float64')

In [25]:
X.shape

(118, 55696)

In [26]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [27]:
# Remove the first two columns (OS and OS.time)
#X=X[:,2:]

In [28]:
X.shape

(118, 55696)

In [29]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [30]:
scaler=StandardScaler().fit(X)

In [31]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [32]:
X=scaler.transform(X)

In [33]:
X[0:4,0:4]

array([[ 0.81361651,  1.22306379, -3.48010217,  0.50589175],
       [-1.22908027, -0.02108731,  0.28734789, -2.08955288],
       [ 0.81361651, -0.7209223 ,  0.28734789, -2.08955288],
       [ 0.81361651,  0.13443158,  0.28734789,  0.50589175]])

In [34]:
X.shape

(118, 55696)

In [35]:
math.ceil(len(gene_exp.columns)**0.5)

236

In [36]:
score_tst_list = []
score_dev_list = []

#le, wi = 20, 5

# 236x236 is 55696

#le, wi = 10, 10
#le, wi = 236, 236
le, wi = math.ceil(len(gene_exp.columns)**0.5), math.ceil(len(gene_exp.columns)**0.5)

conv1_size=(1, wi)
conv2_size=(wi, 1)
input_shape = (le, wi, 1)

# using just 1 loop for now
for i in range(0,2):
        print("Range ")
        ci_tst_list = []
        ci_dev_list = []
        kf = StratifiedKFold(n_splits=5,random_state=1,shuffle=True)
        fold = 0
        for trn_index, tst_index in kf.split(X,E):
            print("Index ")
            fold +=1
            x_tst=X[tst_index]
            c_tst=E[tst_index]
            s_tst=Y[tst_index]

            x_trn, x_dev ,c_trn, c_dev , s_trn, s_dev=train_test_split(
                X[trn_index],E[trn_index],Y[trn_index],test_size=0.1,
                stratify=E[trn_index],random_state=1)

            sort_idx = np.argsort(s_trn)[::-1]
            x_trn = x_trn[sort_idx]
            s_trn = s_trn[sort_idx]
            c_trn = c_trn[sort_idx]

            x_trn = np.reshape(x_trn, (-1, le, wi))
            x_dev = np.reshape(x_dev, (-1, le, wi))
            x_tst = np.reshape(x_tst, (-1, le, wi))

            x_trn = x_trn.reshape(x_trn.shape[0], le, wi, 1)
            x_dev = x_dev.reshape(x_dev.shape[0], le, wi, 1)
            x_tst = x_tst.reshape(x_tst.shape[0], le, wi, 1)
        
            #fit
            data = (x_trn, c_trn, s_trn, x_dev, c_dev, s_dev)
            modelpath = save_path+"%s_fold_%s_repeat_%s_%s.hdf5" % (
                cancer_name,fold,i+1,le*wi)
            checkpoint = MyCallback(modelpath, data)
            
            
            

            
            
            conv1=128
            #conv2=8
            conv2=128
            #dense=32
            dense=64
            input_img = Input(input_shape)
            tower_1 = Conv2D(conv1, conv1_size, activation='relu')(input_img)
            tower_1 = MaxPooling2D(1, 2)(tower_1)
            tower_1 = Flatten()(tower_1)
            tower_2 = Conv2D(conv2, conv2_size, activation='relu')(input_img)
            tower_2 = MaxPooling2D(1, 2)(tower_2)
            tower_2 = Flatten()(tower_2)
            output = concatenate([tower_1, tower_2], axis=1)
            out1 = Dense(dense, activation='relu')(output)
            last_layer = Dense(1, kernel_initializer='zeros', bias_initializer='zeros')(out1)
            model = Model(inputs=[input_img], outputs=last_layer)
            
            
            #conv1=128
            #dense=128
            #input_img = Input(input_shape)
            #tower = Conv2D(conv1, conv1_size, activation='relu')(input_img)
            #tower1 = MaxPooling2D(1, 2)(tower)
            #tower2 = Flatten()(tower1)
            #out = Dense(dense, activation='relu')(tower2)
            #last_layer = Dense(1, kernel_initializer='zeros', bias_initializer='zeros')(out)
            #model = Model(inputs=[input_img], outputs=last_layer)


            #loss
            #def nll(E, NUM_E):
            #    def loss(y_true, y_pred):
            #        hazard_ratio = tf.squeeze(tf.exp(y_pred))
            #        log_risk = tf.math.log(tf.math.cumsum(hazard_ratio))
            #        uncensored_likelihood = tf.subtract(tf.squeeze(y_pred),log_risk)
            #        censored_likelihood = uncensored_likelihood * E
            #        neg_likelihood = -tf.reduce_sum(censored_likelihood) / NUM_E
            #        return neg_likelihood
            #    return loss            
            
            model.compile(loss=[nll(c_trn, np.sum(c_trn))],optimizer="adam")
            #print(model.summary())
            
            
            print('Training...')
            history = model.fit(x_trn, s_trn, batch_size=len(x_trn),
                                epochs=100,verbose=0,callbacks=[checkpoint], shuffle=False)
            model.load_weights(modelpath)
        
            hr_pred=model.predict(x_dev,batch_size=1, verbose=1)
            hr_pred=np.exp(hr_pred)
            #print(hr_pred, c_dev, s_dev)
            print(pd.DataFrame({ 
                'hr_pred': [item for row in hr_pred for item in row], 's_dev': s_dev, 'c_dev': c_dev }))

            
            #fig,ax = plt.subplots(1)
            #ax.scatter(hr_pred,s_dev)
            ##log_pred = [-np.log(p) for p in hr_pred]
            ##ax.scatter(hr_pred,log_pred)
            #plt.title("2D - hr_pred vs s_dev")
            #plt.show()
            
            ci_dev=concordance_index(s_dev,-hr_pred,c_dev)
            
            hr_pred2=model.predict(x_tst,batch_size=1, verbose=1)
            hr_pred2=np.exp(hr_pred2)
            #print(hr_pred2, c_tst, s_tst)
            
            print(pd.DataFrame({ 
                'hr_pred2': [item for row in hr_pred2 for item in row], 's_tst': s_tst, 'c_tst': c_tst }))
            
            #fig,ax = plt.subplots(1)
            #ax.scatter(hr_pred2,s_tst)
            #plt.title("2D - hr_pred2 vs s_tst")
            #plt.show()
            
            ci_tst=concordance_index(s_tst,-hr_pred2,c_tst)
            
            ci_dev_list.append(ci_dev)
            ci_tst_list.append(ci_tst)
            
        score_dev_list.append(ci_dev_list)
        score_tst_list.append(ci_tst_list)

Range
Index
Training...
Early stopping at 37
[Best:on_train_end]

=========================== [Best cindex (epoch = 16)] cindex=0.833333 ==================================
10/10 [==============================] - 0s 2ms/step
     hr_pred      s_dev  c_dev
0   1.002100   6.143866      0
1   1.153433  14.718995      1
2   0.432608   6.800964      0
3   3.581253   2.234133      1
4   2.037359  10.612133      1
5   0.941541   8.969388      0
6   2.655649  12.484862      1
7   1.240481   4.533976      1
8   8.127933   0.427114      0
9  99.790184   2.496972      1
24/24 [==============================] - 0s 2ms/step
     hr_pred2      s_tst  c_tst
0    8.544538   4.369702      1
1   46.463135   8.345145      1
2    6.516208   8.542274      0
3    0.643369   4.566831      0
4    0.437656   4.698251      0
5   61.452484   1.872729      1
6    3.821873  17.840211      1
7    1.631001   7.162368      0
8    3.663625   4.632541      1
9    1.365122   4.862525      1
10   4.710723   6.768109      0
11   9.124912   3.975443      1
12   6.183701   5.486768      0
13   5.684504  16.591725      1
14   0.635396  10.382148      0
15   0.308236  15.770352      1
16   4.304516  14.916125      1
17   0.588311  15.573223      0
18  10.870447   1.182776      1
19   2.771632   0.197129      1
20  14.618812   4.796815      1
21   1.167912   3.646894      1
22   4.362350   9.166517      1
23  71.790367   6.275286      1
Index
Training...
Early stopping at 30
[Best:on_train_end]

=========================== [Best cindex (epoch = 9)] cindex=0.739130 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.961027   4.698251      0
1  6.203858   2.496972      1
2  1.699361   8.805113      0
3  1.313836  11.236376      1
4  1.214981  10.940682      1
5  0.989237   4.566831      0
6  2.614560   4.369702      1
7  1.975636   9.166517      1
8  2.443851   8.542274      0
9  8.058749  12.944831      1
24/24 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   2.005112  14.718995      1
1   1.233689  47.573895      1
2   1.747949   5.421059      0
3   2.590145   2.825521      0
4   0.964714   8.969388      0
5   2.005723   2.726957      1
6   8.241275   2.562682      1
7   1.778590  28.912312      1
8   2.910475  21.881363      1
9   4.788764  25.363983      1
10  1.686253   9.396501      0
11  2.814719   9.856470      1
12  2.231191  21.289975      1
13  0.980566   2.858376      1
14  1.726468   1.215631      0
15  1.084032  11.269231      1
16  2.762853  11.006391      1
17  1.820764  13.634783      0
18  3.517721  15.934627      1
19  4.259056   8.837968      1
20  3.325308   8.870823      0
21  1.420592   5.421059      0
22  1.377208  13.339089      1
23  1.460004   4.533976      1
Index
Training...
Early stopping at 21
[Best:on_train_end]

=========================== [Best cindex (epoch = 0)] cindex=0.769231 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.000283  34.891904      1
1  1.000122  28.912312      1
2  0.999622   6.800964      0
3  1.000745  14.718995      1
4  1.000575   3.088361      1
5  1.000362   7.162368      0
6  1.000008  47.573895      1
7  1.000604  11.729199      1
8  0.999329   4.698251      0
9  1.000551   4.928235      1
24/24 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   1.001231   2.496972      1
1   0.999928  16.197466      0
2   0.999987   7.162368      0
3   1.000421  12.484862      1
4   1.000099   9.265082      0
5   1.000896   3.548329      1
6   1.000692   3.745459      1
7   0.999914   6.143866      0
8   1.001926   3.121215      1
9   1.000672   3.219780      1
10  1.001085   0.952792      1
11  1.000125  11.236376      1
12  1.001381   5.388204      1
13  0.999954   7.622337      1
14  1.000495   3.909733      1
15  1.000524   9.659341      0
16  1.000145  14.850415      0
17  1.000427   1.577035      0
18  1.000803  40.510092      1
19  1.000476  16.066046      1
20  1.001184   5.158219      1
21  1.000547  10.480713      0
22  1.000180  11.532070      0
23  1.000656  20.534312      1
Index
Training...
Early stopping at 29
[Best:on_train_end]

=========================== [Best cindex (epoch = 8)] cindex=0.848485 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  3.739599   2.562682      1
1  1.345491  14.718995      1
2  1.293464   7.162368      0
3  1.316309  28.912312      1
4  1.079656  14.521866      1
5  1.072744   6.143866      0
6  2.476823   4.533976      1
7  1.623009   3.646894      1
8  3.182205   8.542274      0
9  5.333949   2.496972      1
23/23 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   1.148310  15.441803      0
1   1.582146  11.893474      1
2   5.931525  10.283584      1
3   3.117147  13.601929      1
4   1.740996   1.084212      1
5   1.035550   4.928235      1
6   1.132068   5.946737      0
7   2.716115   0.427114      0
8   1.073906  11.729199      1
9   2.735837   8.805113      0
10  1.280776   2.234133      1
11  1.202317  17.478807      1
12  1.712149  29.010877      1
13  2.392461   4.074008      1
14  1.062205   5.421059      0
15  1.373385   5.059655      1
16  1.245677  14.029042      1
17  1.373211   7.589482      1
18  1.376025   7.293788      0
19  1.040231   2.529827      0
20  1.109927  15.376093      1
21  1.341954  11.729199      0
22  1.152899   0.854227      1
Index
Training...
Early stopping at 38
[Best:on_train_end]

=========================== [Best cindex (epoch = 17)] cindex=0.828571 ==================================
10/10 [==============================] - 0s 2ms/step
      hr_pred      s_dev  c_dev
0   10.325128   2.726957      1
1    1.480457  14.718995      1
2    1.799404   4.566831      0
3    0.755905  17.840211      1
4   55.022301   2.562682      1
5    0.661836   8.969388      0
6    0.162836   4.928235      1
7    1.630792   4.533976      1
8    5.059432   8.805113      0
9  535.911682   2.496972      1
23/23 [==============================] - 0s 2ms/step
      hr_pred2      s_tst  c_tst
0   665.285950  12.944831      1
1     0.337499   8.509419      0
2     0.027675   6.800964      0
3    27.394566   4.533976      1
4     0.863159  10.612133      1
5     1.343722  10.940682      1
6     1.844847  34.891904      1
7     0.401572  14.521866      1
8     2.623873  14.916125      1
9     0.079869  13.766203      1
10    0.849635  15.934627      1
11    0.519038   0.164274      1
12   21.489712   8.870823      1
13    0.359718   1.215631      0
14    5.454192   2.529827      1
15    5.296706   4.763960      0
16    0.461206   5.256784      0
17    0.828033   9.790760      0
18    0.582469   4.665396      1
19    0.499007   7.359498      0
20    5.146913   6.045302      0
21   40.659950   3.088361      1
22    0.508141   5.913882      1
Range
Index
Training...
Early stopping at 39
[Best:on_train_end]

=========================== [Best cindex (epoch = 18)] cindex=0.833333 ==================================
10/10 [==============================] - 0s 2ms/step
      hr_pred      s_dev  c_dev
0    0.473506   6.143866      0
1    0.500581  14.718995      1
2    0.189026   6.800964      0
3    1.686628   2.234133      1
4    0.961734  10.612133      1
5    0.463214   8.969388      0
6    1.088433  12.484862      1
7    0.585903   4.533976      1
8    7.109176   0.427114      0
9  155.648941   2.496972      1
24/24 [==============================] - 0s 2ms/step
      hr_pred2      s_tst  c_tst
0    10.346457   4.369702      1
1    67.209602   8.345145      1
2     7.181466   8.542274      0
3     0.219931   4.566831      0
4     0.289904   4.698251      0
5    61.949253   1.872729      1
6     2.414508  17.840211      1
7     0.686930   7.162368      0
8     2.040339   4.632541      1
9     0.680403   4.862525      1
10    3.663276   6.768109      0
11    7.290152   3.975443      1
12    4.242116   5.486768      0
13    4.223481  16.591725      1
14    0.171117  10.382148      0
15    0.109782  15.770352      1
16    1.471431  14.916125      1
17    0.256840  15.573223      0
18    8.030707   1.182776      1
19    1.596892   0.197129      1
20   17.760340   4.796815      1
21    0.385667   3.646894      1
22    3.602097   9.166517      1
23  267.262970   6.275286      1
Index

Training...
Early stopping at 30
[Best:on_train_end]

=========================== [Best cindex (epoch = 9)] cindex=0.739130 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  2.095888   4.698251      0
1  7.101576   2.496972      1
2  1.819917   8.805113      0
3  1.488925  11.236376      1
4  1.182656  10.940682      1
5  1.021854   4.566831      0
6  2.224957   4.369702      1
7  1.848637   9.166517      1
8  2.070571   8.542274      0
9  8.618307  12.944831      1
24/24 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   1.897347  14.718995      1
1   1.225711  47.573895      1
2   1.734377   5.421059      0
3   2.506797   2.825521      0
4   1.008608   8.969388      0
5   2.078109   2.726957      1
6   8.363970   2.562682      1
7   1.861833  28.912312      1
8   3.057450  21.881363      1
9   4.475787  25.363983      1
10  1.672120   9.396501      0
11  2.749835   9.856470      1
12  2.324497  21.289975      1
13  0.919182   2.858376      1
14  1.671749   1.215631      0
15  0.978971  11.269231      1
16  2.845262  11.006391      1
17  1.877618  13.634783      0
18  3.257268  15.934627      1
19  3.480200   8.837968      1
20  3.027626   8.870823      0
21  1.446865   5.421059      0
22  1.348930  13.339089      1
23  1.316635   4.533976      1
Index
Training...
Early stopping at 40
[Best:on_train_end]

=========================== [Best cindex (epoch = 19)] cindex=0.807692 ==================================
10/10 [==============================] - 0s 2ms/step
       hr_pred      s_dev  c_dev
0    27.857798  34.891904      1
1    31.449606  28.912312      1
2    16.980907   6.800964      0
3    33.703205  14.718995      1
4    93.763504   3.088361      1
5     2.718418   7.162368      0
6     9.734646  47.573895      1
7     3.450778  11.729199      1
8  1272.851562   4.698251      0
9    37.919731   4.928235      1
24/24 [==============================] - 0s 2ms/step
       hr_pred2      s_tst  c_tst
0    157.396362   2.496972      1
1     44.477097  16.197466      0
2     12.218381   7.162368      0
3     13.640738  12.484862      1
4    150.409332   9.265082      0
5     69.902084   3.548329      1
6      6.953159   3.745459      1
7      3.220934   6.143866      0
8   1007.834961   3.121215      1
9      9.148770   3.219780      1
10   368.947937   0.952792      1
11     3.666588  11.236376      1
12    27.006119   5.388204      1
13    31.087543   7.622337      1
14   571.351318   3.909733      1
15    84.029358   9.659341      0
16    21.000763  14.850415      0
17    12.970377   1.577035      0
18    63.028419  40.510092      1
19     6.313783  16.066046      1
20   184.835236   5.158219      1
21    38.784233  10.480713      0
22    30.358547  11.532070      0
23    94.738388  20.534312      1
Index
Training...
Early stopping at 28
[Best:on_train_end]

=========================== [Best cindex (epoch = 7)] cindex=0.818182 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  3.611434   2.562682      1
1  1.230083  14.718995      1
2  1.230078   7.162368      0
3  1.205300  28.912312      1
4  1.041423  14.521866      1
5  1.121524   6.143866      0
6  1.986690   4.533976      1
7  1.673212   3.646894      1
8  3.733807   8.542274      0
9  3.877227   2.496972      1
23/23 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   1.159713  15.441803      0
1   1.292835  11.893474      1
2   4.531161  10.283584      1
3   3.196658  13.601929      1
4   1.650405   1.084212      1
5   1.016179   4.928235      1
6   1.086361   5.946737      0
7   2.662718   0.427114      0
8   1.036668  11.729199      1
9   2.322287   8.805113      0
10  1.161724   2.234133      1
11  1.204476  17.478807      1
12  1.453270  29.010877      1
13  2.149360   4.074008      1
14  1.297178   5.421059      0
15  1.361402   5.059655      1
16  1.139648  14.029042      1
17  1.199956   7.589482      1
18  1.210150   7.293788      0
19  1.000389   2.529827      0
20  1.082062  15.376093      1
21  1.131153  11.729199      0
22  1.160970   0.854227      1
Index
Training...
Early stopping at 34
[Best:on_train_end]

=========================== [Best cindex (epoch = 13)] cindex=0.857143 ==================================
10/10 [==============================] - 0s 2ms/step
     hr_pred      s_dev  c_dev
0   1.646513   2.726957      1
1   0.615246  14.718995      1
2   0.664799   4.566831      0
3   0.528686  17.840211      1
4   2.293478   2.562682      1
5   0.493810   8.969388      0
6   0.225980   4.928235      1
7   0.667797   4.533976      1
8   1.291392   8.805113      0
9  17.776157   2.496972      1
23/23 [==============================] - 0s 2ms/step
     hr_pred2      s_tst  c_tst
0   13.832812  12.944831      1
1    0.351046   8.509419      0
2    0.057539   6.800964      0
3    3.558461   4.533976      1
4    0.422839  10.612133      1
5    0.828526  10.940682      1
6    1.060894  34.891904      1
7    0.342581  14.521866      1
8    1.257507  14.916125      1
9    0.141892  13.766203      1
10   0.693757  15.934627      1
11   0.321429   0.164274      1
12   3.453142   8.870823      1
13   0.316105   1.215631      0
14   1.518780   2.529827      1
15   1.664712   4.763960      0
16   0.343548   5.256784      0
17   0.612544   9.790760      0
18   0.437179   4.665396      1
19   0.513647   7.359498      0
20   1.375847   6.045302      0
21   4.080870   3.088361      1
22   0.211274   5.913882      1


If the hazard ratio is less than 1, then the predictor is protective (i.e., associated with improved survival) and if the hazard ratio is greater than 1, then the predictor is associated with increased risk (or decreased survival).