

A convolutional neural network model for survival prediction based on prognosis-related cascaded Wx feature selection

https://www.laboratoryinvestigation.org/article/S0023-6837(22)00114-3/fulltext

https://github.com/wangwangCCChen/CNN-Cox

https://github.com/ucsffrancislab/CNN-Cox

In [1]:
#from Trainmodel import traindcnncoxmodel,traincnncoxmodel
#from utils import avgcindex

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1" 
import math
import numpy as np
import pandas as pd
#from model import cnncox,dcnncox,nncox
from earlystoping import MyCallback
from utils import nll,avgcindex,setup_seed
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold,train_test_split
from lifelines.utils import concordance_index
import matplotlib.pyplot as plt
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense,Dropout,Input,Flatten,concatenate
from tensorflow.keras.regularizers import l2

2024-04-18 13:59:52.501652: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


GENE_2_counts_normalized.subject_unique.metadata.all.tsv

was created from the REdiscoverTE output converted to a tsv.

The metadata came from Eduardo's initial gbm_train/gbm_test data files.

In [3]:

cancer_name='TCGA'
Cindex=[]

current_path='../data/our/'
output_path=current_path+'/RE_all_2_counts_normalized.subject_unique.metadata.all.tsv'
save_path="../save model/our/my2DCNNCox/"
os.makedirs(save_path,exist_ok=True)

In [4]:

seed=42

setup_seed(seed)

df_exp=pd.read_csv(output_path,index_col=0,sep="\t",low_memory=False)

In [5]:
df_exp.head()

,sex,IDH,x1p19q,TERT,MGMT,Age,Survival_months,Vital_status,EGFR_re,CDKN2A_re,...,tRNA-Thr-ACG,tRNA-Thr-ACG_,tRNA-Thr-ACY,tRNA-Thr-ACY_,tRNA-Trp-TGG,tRNA-Tyr-TAC,tRNA-Tyr-TAT,tRNA-Val-GTA,tRNA-Val-GTG,tRNA-Val-GTY
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,male,WT,non-codel,NaN,Unmethylated,78,14.718995,1,Wildtype,Deleted,...,0,0,0,0.0,0,0.0,0,0,0.0,0
02-0055,female,WT,non-codel,NaN,Unmethylated,62,2.496972,1,Amplified,Wildtype,...,0,0,0,0.0,0,1.0,0,0,1.0,0
02-2485,male,WT,non-codel,Mutant,Unmethylated,53,15.441803,0,Amplified,Wildtype,...,0,0,0,0.0,0,2.0,0,0,1.0,0
02-2486,male,WT,non-codel,NaN,Unmethylated,64,16.197466,0,Amplified,Deleted,...,0,0,0,0.0,0,0.0,0,0,1.0,0
06-0125,female,WT,non-codel,Mutant,Methylated,63,47.573895,1,Amplified,Deleted,...,0,0,0,0.0,0,0.0,0,0,0.0,0

In [6]:
df_exp.drop(columns=['IDH','x1p19q','TERT','MGMT'],inplace=True)
df_exp.head()


# EGFR_re, CDKN2A_re ?

# what is the column "NA" from?

,sex,Age,Survival_months,Vital_status,EGFR_re,CDKN2A_re,(A)n,(AAAAAAG)n,(AAAAAC)n,(AAAAACA)n,...,tRNA-Thr-ACG,tRNA-Thr-ACG_,tRNA-Thr-ACY,tRNA-Thr-ACY_,tRNA-Trp-TGG,tRNA-Tyr-TAC,tRNA-Tyr-TAT,tRNA-Val-GTA,tRNA-Val-GTG,tRNA-Val-GTY
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,male,78,14.718995,1,Wildtype,Deleted,1.997,0,0,0,...,0,0,0,0.0,0,0.0,0,0,0.0,0
02-0055,female,62,2.496972,1,Amplified,Wildtype,0.000,0,0,0,...,0,0,0,0.0,0,1.0,0,0,1.0,0
02-2485,male,53,15.441803,0,Amplified,Wildtype,0.000,0,0,0,...,0,0,0,0.0,0,2.0,0,0,1.0,0
02-2486,male,64,16.197466,0,Amplified,Deleted,0.000,0,1,0,...,0,0,0,0.0,0,0.0,0,0,1.0,0
06-0125,female,63,47.573895,1,Amplified,Deleted,0.000,0,0,0,...,0,0,0,0.0,0,0.0,0,0,0.0,0

In [7]:
#df_exp.fillna(0,inplace=True)

if 'sex' in df_exp.columns:
    df_exp['sex'].replace(to_replace={'female':0, 'male':1}, inplace=True)
if 'MGMT' in df_exp.columns:
    df_exp['MGMT'].replace(to_replace={'Unmethylated':0, 'Methylated':1}, inplace=True)
if 'EGFR_re' in df_exp.columns:
    df_exp['EGFR_re'].replace(to_replace={"Wildtype":0, "Amplified":1}, inplace=True)
if 'CDKN2A_re' in df_exp.columns:
    df_exp['CDKN2A_re'].replace(to_replace={"Wildtype":0, "Amplified":1, "Deleted":2}, inplace=True)

df_exp.head()

,sex,Age,Survival_months,Vital_status,EGFR_re,CDKN2A_re,(A)n,(AAAAAAG)n,(AAAAAC)n,(AAAAACA)n,...,tRNA-Thr-ACG,tRNA-Thr-ACG_,tRNA-Thr-ACY,tRNA-Thr-ACY_,tRNA-Trp-TGG,tRNA-Tyr-TAC,tRNA-Tyr-TAT,tRNA-Val-GTA,tRNA-Val-GTG,tRNA-Val-GTY
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,1,78,14.718995,1,0,2,1.997,0,0,0,...,0,0,0,0.0,0,0.0,0,0,0.0,0
02-0055,0,62,2.496972,1,1,0,0.000,0,0,0,...,0,0,0,0.0,0,1.0,0,0,1.0,0
02-2485,1,53,15.441803,0,1,0,0.000,0,0,0,...,0,0,0,0.0,0,2.0,0,0,1.0,0
02-2486,1,64,16.197466,0,1,2,0.000,0,1,0,...,0,0,0,0.0,0,0.0,0,0,1.0,0
06-0125,0,63,47.573895,1,1,2,0.000,0,0,0,...,0,0,0,0.0,0,0.0,0,0,0.0,0

In [8]:
gene_exp=df_exp.dropna(axis=0,subset = ["Vital_status", "Survival_months"])
E=np.array(gene_exp.pop("Vital_status"))
Y=np.array(gene_exp.pop("Survival_months"))

In [9]:
gene_exp.head()

,sex,Age,EGFR_re,CDKN2A_re,(A)n,(AAAAAAG)n,(AAAAAC)n,(AAAAACA)n,(AAAAACC)n,(AAAAAG)n,...,tRNA-Thr-ACG,tRNA-Thr-ACG_,tRNA-Thr-ACY,tRNA-Thr-ACY_,tRNA-Trp-TGG,tRNA-Tyr-TAC,tRNA-Tyr-TAT,tRNA-Val-GTA,tRNA-Val-GTG,tRNA-Val-GTY
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,1,78,0,2,1.997,0,0,0,0,1,...,0,0,0,0.0,0,0.0,0,0,0.0,0
02-0055,0,62,1,0,0.000,0,0,0,0,0,...,0,0,0,0.0,0,1.0,0,0,1.0,0
02-2485,1,53,1,0,0.000,0,0,0,0,0,...,0,0,0,0.0,0,2.0,0,0,1.0,0
02-2486,1,64,1,2,0.000,0,1,0,0,0,...,0,0,0,0.0,0,0.0,0,0,1.0,0
06-0125,0,63,1,2,0.000,0,0,0,0,0,...,0,0,0,0.0,0,0.0,0,0,0.0,0

In [10]:
E.shape

(118,)

In [11]:
E[0:15]

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0])

In [12]:
E

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
Y.shape

(118,)

In [14]:
Y[0:15]

array([14.7189952,  2.4969724, 15.441803 , 16.1974657, 47.5738952,
       12.9448306, 11.8934738, 10.2835837,  7.1623682,  5.4210585,
       13.6019286,  1.0842117, 12.484862 ,  4.928235 ,  9.2650818])

In [15]:
len(gene_exp.columns)

6519

In [16]:
math.ceil(len(gene_exp.columns)**0.5)

81

In [17]:
math.ceil(len(gene_exp.columns)**0.5)**2

6561


Add a number of columns to make the dataframe column count a square ( 236 x 236 = 55696 )

In [18]:
#for i in range(55696-len(gene_exp.columns)):
#    print("extra"+str(i), end=", ")
#    col=str("extra"+str(i))
#    gene_exp["extra"+str(i)]=0

extra=["extra"+str(i) for i in range( (math.ceil(len(gene_exp.columns)**0.5)**2) - len(gene_exp.columns) )]
#gene_exp[extra]=0

gene_exp=pd.concat([gene_exp, pd.DataFrame(columns = extra)]).fillna(0)

#gene_exp.assign(extra=0)
#gene_exp.insert(2, "expenditure", 4500, allow_duplicates=False)

In [19]:
gene_exp.columns

Index(['sex', 'Age', 'EGFR_re', 'CDKN2A_re', '(A)n', '(AAAAAAG)n', '(AAAAAC)n',
       '(AAAAACA)n', '(AAAAACC)n', '(AAAAAG)n',
       ...
       'extra32', 'extra33', 'extra34', 'extra35', 'extra36', 'extra37',
       'extra38', 'extra39', 'extra40', 'extra41'],
      dtype='object', length=6561)

In [20]:
len(gene_exp.columns)

6561

In [21]:
X=np.array(gene_exp)

In [22]:
X.shape

(118, 6561)

In [23]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [24]:
X=X.astype('float64')

In [25]:
X.shape

(118, 6561)

In [26]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [27]:
# Remove the first two columns (OS and OS.time)
#X=X[:,2:]

In [28]:
X.shape

(118, 6561)

In [29]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [30]:
scaler=StandardScaler().fit(X)

In [31]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [32]:
X=scaler.transform(X)

In [33]:
X[0:4,0:4]

array([[ 0.81361651,  1.22306379, -3.48010217,  0.50589175],
       [-1.22908027, -0.02108731,  0.28734789, -2.08955288],
       [ 0.81361651, -0.7209223 ,  0.28734789, -2.08955288],
       [ 0.81361651,  0.13443158,  0.28734789,  0.50589175]])

In [34]:
X.shape

(118, 6561)

In [35]:
math.ceil(len(gene_exp.columns)**0.5)

81

In [36]:
score_tst_list = []
score_dev_list = []

#le, wi = 20, 5

# 236x236 is 55696

#le, wi = 10, 10
#le, wi = 236, 236
le, wi = math.ceil(len(gene_exp.columns)**0.5), math.ceil(len(gene_exp.columns)**0.5)

conv1_size=(1, wi)
conv2_size=(wi, 1)
input_shape = (le, wi, 1)

# using just 1 loop for now
for i in range(0,2):
        print("Range ")
        ci_tst_list = []
        ci_dev_list = []
        kf = StratifiedKFold(n_splits=5,random_state=1,shuffle=True)
        fold = 0
        for trn_index, tst_index in kf.split(X,E):
            print("Index ")
            fold +=1
            x_tst=X[tst_index]
            c_tst=E[tst_index]
            s_tst=Y[tst_index]

            x_trn, x_dev ,c_trn, c_dev , s_trn, s_dev=train_test_split(
                X[trn_index],E[trn_index],Y[trn_index],test_size=0.1,
                stratify=E[trn_index],random_state=1)

            sort_idx = np.argsort(s_trn)[::-1]
            x_trn = x_trn[sort_idx]
            s_trn = s_trn[sort_idx]
            c_trn = c_trn[sort_idx]

            x_trn = np.reshape(x_trn, (-1, le, wi))
            x_dev = np.reshape(x_dev, (-1, le, wi))
            x_tst = np.reshape(x_tst, (-1, le, wi))

            x_trn = x_trn.reshape(x_trn.shape[0], le, wi, 1)
            x_dev = x_dev.reshape(x_dev.shape[0], le, wi, 1)
            x_tst = x_tst.reshape(x_tst.shape[0], le, wi, 1)
        
            #fit
            data = (x_trn, c_trn, s_trn, x_dev, c_dev, s_dev)
            modelpath = save_path+"%s_fold_%s_repeat_%s_%s.hdf5" % (
                cancer_name,fold,i+1,le*wi)
            checkpoint = MyCallback(modelpath, data)
            
            
            

            
            
            conv1=128
            #conv2=8
            conv2=128
            #dense=32
            dense=64
            input_img = Input(input_shape)
            tower_1 = Conv2D(conv1, conv1_size, activation='relu')(input_img)
            tower_1 = MaxPooling2D(1, 2)(tower_1)
            tower_1 = Flatten()(tower_1)
            tower_2 = Conv2D(conv2, conv2_size, activation='relu')(input_img)
            tower_2 = MaxPooling2D(1, 2)(tower_2)
            tower_2 = Flatten()(tower_2)
            output = concatenate([tower_1, tower_2], axis=1)
            out1 = Dense(dense, activation='relu')(output)
            last_layer = Dense(1, kernel_initializer='zeros', bias_initializer='zeros')(out1)
            model = Model(inputs=[input_img], outputs=last_layer)
            
            
            #conv1=128
            #dense=128
            #input_img = Input(input_shape)
            #tower = Conv2D(conv1, conv1_size, activation='relu')(input_img)
            #tower1 = MaxPooling2D(1, 2)(tower)
            #tower2 = Flatten()(tower1)
            #out = Dense(dense, activation='relu')(tower2)
            #last_layer = Dense(1, kernel_initializer='zeros', bias_initializer='zeros')(out)
            #model = Model(inputs=[input_img], outputs=last_layer)


            #loss
            #def nll(E, NUM_E):
            #    def loss(y_true, y_pred):
            #        hazard_ratio = tf.squeeze(tf.exp(y_pred))
            #        log_risk = tf.math.log(tf.math.cumsum(hazard_ratio))
            #        uncensored_likelihood = tf.subtract(tf.squeeze(y_pred),log_risk)
            #        censored_likelihood = uncensored_likelihood * E
            #        neg_likelihood = -tf.reduce_sum(censored_likelihood) / NUM_E
            #        return neg_likelihood
            #    return loss            
            
            model.compile(loss=[nll(c_trn, np.sum(c_trn))],optimizer="adam")
            #print(model.summary())
            
            
            print('Training...')
            history = model.fit(x_trn, s_trn, batch_size=len(x_trn),
                                epochs=100,verbose=0,callbacks=[checkpoint], shuffle=False)
            model.load_weights(modelpath)
        
            hr_pred=model.predict(x_dev,batch_size=1, verbose=1)
            hr_pred=np.exp(hr_pred)
            #print(hr_pred, c_dev, s_dev)
            print(pd.DataFrame({ 
                'hr_pred': [item for row in hr_pred for item in row], 's_dev': s_dev, 'c_dev': c_dev }))

            
            #fig,ax = plt.subplots(1)
            #ax.scatter(hr_pred,s_dev)
            ##log_pred = [-np.log(p) for p in hr_pred]
            ##ax.scatter(hr_pred,log_pred)
            #plt.title("2D - hr_pred vs s_dev")
            #plt.show()
            
            ci_dev=concordance_index(s_dev,-hr_pred,c_dev)
            
            hr_pred2=model.predict(x_tst,batch_size=1, verbose=1)
            hr_pred2=np.exp(hr_pred2)
            #print(hr_pred2, c_tst, s_tst)
            
            print(pd.DataFrame({ 
                'hr_pred2': [item for row in hr_pred2 for item in row], 's_tst': s_tst, 'c_tst': c_tst }))
            
            #fig,ax = plt.subplots(1)
            #ax.scatter(hr_pred2,s_tst)
            #plt.title("2D - hr_pred2 vs s_tst")
            #plt.show()
            
            ci_tst=concordance_index(s_tst,-hr_pred2,c_tst)
            
            ci_dev_list.append(ci_dev)
            ci_tst_list.append(ci_tst)
            
        score_dev_list.append(ci_dev_list)
        score_tst_list.append(ci_tst_list)

Range
Index
Training...
Early stopping at 57
[Best:on_train_end]

=========================== [Best cindex (epoch = 36)] cindex=0.750000 ==================================
10/10 [==============================] - 0s 1ms/step
     hr_pred      s_dev  c_dev
0   0.111522   6.143866      0
1   1.715254  14.718995      1
2  25.714205   6.800964      0
3   1.747331   2.234133      1
4   6.181767  10.612133      1
5   0.093227   8.969388      0
6   0.660309  12.484862      1
7  16.286448   4.533976      1
8   1.030789   0.427114      0
9  58.598534   2.496972      1
24/24 [==============================] - 0s 1ms/step
      hr_pred2      s_tst  c_tst
0    21.494476   4.369702      1
1    34.718746   8.345145      1
2    19.598642   8.542274      0
3     6.275342   4.566831      0
4    97.857544   4.698251      0
5   123.043350   1.872729      1
6     6.224980  17.840211      1
7    14.374928   7.162368      0
8   125.663437   4.632541      1
9     7.920939   4.862525      1
10   27.334799   6.768109      0
11  199.377457   3.975443      1
12   13.139618   5.486768      0
13   32.342388  16.591725      1
14    0.821988  10.382148      0
15    0.553695  15.770352      1
16    5.551079  14.916125      1
17    2.064144  15.573223      0
18    6.173775   1.182776      1
19    1.792278   0.197129      1
20    7.162088   4.796815      1
21    4.809383   3.646894      1
22    3.716999   9.166517      1
23  227.573883   6.275286      1
Index
Training...
Early stopping at 57
[Best:on_train_end]

=========================== [Best cindex (epoch = 36)] cindex=0.695652 ==================================
10/10 [==============================] - 0s 1ms/step
     hr_pred      s_dev  c_dev
0  11.772638   4.698251      0
1   3.807757   2.496972      1
2   0.232721   8.805113      0
3   0.244279  11.236376      1
4   0.010994  10.940682      1
5   0.605123   4.566831      0
6  17.237236   4.369702      1
7   9.781164   9.166517      1
8   0.126117   8.542274      0
9   7.108500  12.944831      1
24/24 [==============================] - 0s 1ms/step
       hr_pred2      s_tst  c_tst
0      6.242081  14.718995      1
1      4.116924  47.573895      1
2      3.487676   5.421059      0
3    327.666870   2.825521      0
4      0.054161   8.969388      0
5      2.279904   2.726957      1
6     52.407135   2.562682      1
7      0.342483  28.912312      1
8     52.804203  21.881363      1
9     26.493370  25.363983      1
10     1.261634   9.396501      0
11     1.428523   9.856470      1
12  2028.409668  21.289975      1
13     0.006748   2.858376      1
14     0.067632   1.215631      0
15     0.272510  11.269231      1
16     5.323611  11.006391      1
17     1.579883  13.634783      0
18    12.162283  15.934627      1
19    74.545807   8.837968      1
20     2.317178   8.870823      0
21     0.097942   5.421059      0
22     0.671585  13.339089      1
23     0.864285   4.533976      1
Index
Training...
Early stopping at 21
[Best:on_train_end]

=========================== [Best cindex (epoch = 0)] cindex=0.653846 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.000985  34.891904      1
1  1.000837  28.912312      1
2  1.001036   6.800964      0
3  1.001151  14.718995      1
4  1.000923   3.088361      1
5  1.000840   7.162368      0
6  1.000529  47.573895      1
7  1.000790  11.729199      1
8  1.002257   4.698251      0
9  1.001472   4.928235      1
24/24 [==============================] - 0s 1ms/step
    hr_pred2      s_tst  c_tst
0   1.000832   2.496972      1
1   1.001014  16.197466      0
2   1.000134   7.162368      0
3   1.000497  12.484862      1
4   1.000923   9.265082      0
5   1.000821   3.548329      1
6   1.000707   3.745459      1
7   1.000765   6.143866      0
8   1.001862   3.121215      1
9   1.000468   3.219780      1
10  1.001182   0.952792      1
11  1.000325  11.236376      1
12  1.001117   5.388204      1
13  1.000925   7.622337      1
14  1.001109   3.909733      1
15  1.001048   9.659341      0
16  1.001219  14.850415      0
17  1.000533   1.577035      0
18  1.001040  40.510092      1
19  1.001457  16.066046      1
20  1.000837   5.158219      1
21  1.000415  10.480713      0
22  1.000316  11.532070      0
23  1.002368  20.534312      1
Index
Training...
Early stopping at 57
[Best:on_train_end]

=========================== [Best cindex (epoch = 36)] cindex=0.878788 ==================================
10/10 [==============================] - 0s 2ms/step
     hr_pred      s_dev  c_dev
0  14.305653   2.562682      1
1   0.121253  14.718995      1
2   0.039324   7.162368      0
3   3.885305  28.912312      1
4   0.018265  14.521866      1
5   0.007328   6.143866      0
6   1.218244   4.533976      1
7   4.608145   3.646894      1
8   0.076280   8.542274      0
9  45.542076   2.496972      1
23/23 [==============================] - 0s 1ms/step
      hr_pred2      s_tst  c_tst
0     0.343404  15.441803      0
1    15.981242  11.893474      1
2   103.221489  10.283584      1
3     0.174597  13.601929      1
4     0.005394   1.084212      1
5     0.005153   4.928235      1
6     0.011559   5.946737      0
7     1.143339   0.427114      0
8     0.061834  11.729199      1
9    15.152884   8.805113      0
10    0.133123   2.234133      1
11    0.008335  17.478807      1
12    0.041030  29.010877      1
13    4.799144   4.074008      1
14    0.089859   5.421059      0
15    0.103104   5.059655      1
16    0.201054  14.029042      1
17    0.049880   7.589482      1
18    2.743984   7.293788      0
19    1.664587   2.529827      0
20    0.016356  15.376093      1
21    0.249695  11.729199      0
22    0.011293   0.854227      1
Index
Training...
Early stopping at 32
[Best:on_train_end]

=========================== [Best cindex (epoch = 11)] cindex=0.800000 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.153516   2.726957      1
1  1.080704  14.718995      1
2  1.137789   4.566831      0
3  1.075376  17.840211      1
4  1.226795   2.562682      1
5  0.956236   8.969388      0
6  0.787627   4.928235      1
7  1.284683   4.533976      1
8  1.163262   8.805113      0
9  1.296419   2.496972      1
23/23 [==============================] - 0s 1ms/step
    hr_pred2      s_tst  c_tst
0   1.387662  12.944831      1
1   1.092885   8.509419      0
2   1.022569   6.800964      0
3   1.281420   4.533976      1
4   1.164160  10.612133      1
5   1.150690  10.940682      1
6   1.122725  34.891904      1
7   1.039700  14.521866      1
8   1.109452  14.916125      1
9   1.032414  13.766203      1
10  1.105170  15.934627      1
11  0.702623   0.164274      1
12  1.081729   8.870823      1
13  1.184484   1.215631      0
14  1.150766   2.529827      1
15  1.103707   4.763960      0
16  1.050645   5.256784      0
17  1.146661   9.790760      0
18  1.132164   4.665396      1
19  1.024003   7.359498      0
20  1.277105   6.045302      0
21  1.028649   3.088361      1
22  1.154198   5.913882      1
Range
Index
Training...
Early stopping at 21
[Best:on_train_end]

=========================== [Best cindex (epoch = 0)] cindex=0.666667 ==================================
10/10 [==============================] - 0s 1ms/step
    hr_pred      s_dev  c_dev
0  1.000963   6.143866      0
1  1.000018  14.718995      1
2  1.001012   6.800964      0
3  1.000647   2.234133      1
4  1.000972  10.612133      1
5  1.000193   8.969388      0
6  1.000518  12.484862      1
7  1.000419   4.533976      1
8  1.000773   0.427114      0
9  1.001116   2.496972      1
24/24 [==============================] - 0s 1ms/step
    hr_pred2      s_tst  c_tst
0   1.001166   4.369702      1
1   1.000483   8.345145      1
2   1.001287   8.542274      0
3   1.000388   4.566831      0
4   1.001748   4.698251      0
5   1.001654   1.872729      1
6   1.000666  17.840211      1
7   1.000988   7.162368      0
8   1.000771   4.632541      1
9   1.000957   4.862525      1
10  1.001257   6.768109      0
11  1.001111   3.975443      1
12  1.001714   5.486768      0
13  1.000979  16.591725      1
14  1.001148  10.382148      0
15  1.000895  15.770352      1
16  1.000721  14.916125      1
17  1.000482  15.573223      0
18  1.000350   1.182776      1
19  1.000817   0.197129      1
20  1.000497   4.796815      1
21  1.001261   3.646894      1
22  1.000783   9.166517      1
23  1.001914   6.275286      1
Index

Training...
Early stopping at 49
[Best:on_train_end]

=========================== [Best cindex (epoch = 28)] cindex=0.652174 ==================================
10/10 [==============================] - 0s 1ms/step
       hr_pred      s_dev  c_dev
0  2044.380127   4.698251      0
1    42.150356   2.496972      1
2     7.036440   8.805113      0
3    14.464149  11.236376      1
4     3.824471  10.940682      1
5    11.117813   4.566831      0
6    78.935555   4.369702      1
7    74.585670   9.166517      1
8    15.397472   8.542274      0
9    53.524803  12.944831      1
24/24 [==============================] - 0s 1ms/step
       hr_pred2      s_tst  c_tst
0     54.633255  14.718995      1
1     94.127167  47.573895      1
2     61.035896   5.421059      0
3    187.895966   2.825521      0
4      2.524988   8.969388      0
5     12.365145   2.726957      1
6    273.010162   2.562682      1
7     34.950283  28.912312      1
8    157.016083  21.881363      1
9    236.469971  25.363983      1
10    20.893890   9.396501      0
11    77.094193   9.856470      1
12  1113.766113  21.289975      1
13     4.328810   2.858376      1
14     9.991190   1.215631      0
15    12.342377  11.269231      1
16    23.588461  11.006391      1
17    21.693098  13.634783      0
18    38.792660  15.934627      1
19   189.127823   8.837968      1
20    31.505930   8.870823      0
21     7.069345   5.421059      0
22    17.198566  13.339089      1
23    10.520012   4.533976      1
Index
Training...
Early stopping at 27
[Best:on_train_end]

=========================== [Best cindex (epoch = 6)] cindex=0.500000 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.012100  34.891904      1
1  1.025314  28.912312      1
2  1.227057   6.800964      0
3  1.093141  14.718995      1
4  1.025611   3.088361      1
5  1.019010   7.162368      0
6  1.196404  47.573895      1
7  1.018614  11.729199      1
8  1.621121   4.698251      0
9  1.134472   4.928235      1
24/24 [==============================] - 0s 1ms/step
    hr_pred2      s_tst  c_tst
0   1.033864   2.496972      1
1   1.034140  16.197466      0
2   1.027204   7.162368      0
3   1.069016  12.484862      1
4   1.119278   9.265082      0
5   1.031781   3.548329      1
6   1.132382   3.745459      1
7   1.077784   6.143866      0
8   1.365125   3.121215      1
9   1.014273   3.219780      1
10  1.073709   0.952792      1
11  1.024038  11.236376      1
12  1.020346   5.388204      1
13  1.018904   7.622337      1
14  1.115240   3.909733      1
15  1.090043   9.659341      0
16  1.055403  14.850415      0
17  1.035867   1.577035      0
18  1.093449  40.510092      1
19  1.062336  16.066046      1
20  1.088234   5.158219      1
21  1.060106  10.480713      0
22  1.097981  11.532070      0
23  1.406785  20.534312      1
Index
Training...
Early stopping at 39
[Best:on_train_end]

=========================== [Best cindex (epoch = 18)] cindex=0.848485 ==================================
10/10 [==============================] - 0s 1ms/step
    hr_pred      s_dev  c_dev
0  2.135317   2.562682      1
1  0.802201  14.718995      1
2  0.784998   7.162368      0
3  1.958882  28.912312      1
4  1.094124  14.521866      1
5  0.492719   6.143866      0
6  1.525184   4.533976      1
7  1.439179   3.646894      1
8  1.288925   8.542274      0
9  2.214858   2.496972      1
23/23 [==============================] - 0s 1ms/step
    hr_pred2      s_tst  c_tst
0   0.791858  15.441803      0
1   2.414298  11.893474      1
2   2.776757  10.283584      1
3   0.942756  13.601929      1
4   0.351719   1.084212      1
5   0.541748   4.928235      1
6   0.402085   5.946737      0
7   1.099898   0.427114      0
8   0.832045  11.729199      1
9   1.765789   8.805113      0
10  0.731146   2.234133      1
11  0.515230  17.478807      1
12  0.678391  29.010877      1
13  1.253168   4.074008      1
14  1.036406   5.421059      0
15  1.019753   5.059655      1
16  0.962549  14.029042      1
17  0.929332   7.589482      1
18  1.313971   7.293788      0
19  1.503440   2.529827      0
20  0.458885  15.376093      1
21  1.378692  11.729199      0
22  0.416542   0.854227      1
Index
Training...
Early stopping at 31
[Best:on_train_end]

=========================== [Best cindex (epoch = 10)] cindex=0.628571 ==================================
10/10 [==============================] - 0s 1ms/step
    hr_pred      s_dev  c_dev
0  0.989618   2.726957      1
1  0.878875  14.718995      1
2  0.986970   4.566831      0
3  0.938220  17.840211      1
4  0.836810   2.562682      1
5  0.818494   8.969388      0
6  0.674314   4.928235      1
7  1.084481   4.533976      1
8  1.018017   8.805113      0
9  1.097724   2.496972      1
23/23 [==============================] - 0s 1ms/step
    hr_pred2      s_tst  c_tst
0   1.095010  12.944831      1
1   0.939107   8.509419      0
2   0.778433   6.800964      0
3   1.060714   4.533976      1
4   0.972447  10.612133      1
5   0.981241  10.940682      1
6   1.026193  34.891904      1
7   0.926442  14.521866      1
8   0.979991  14.916125      1
9   0.898620  13.766203      1
10  0.991342  15.934627      1
11  0.472114   0.164274      1
12  0.907583   8.870823      1
13  0.977125   1.215631      0
14  1.034507   2.529827      1
15  1.003642   4.763960      0
16  0.892789   5.256784      0
17  1.022385   9.790760      0
18  1.016734   4.665396      1
19  0.874221   7.359498      0
20  1.050314   6.045302      0
21  0.934215   3.088361      1
22  0.776532   5.913882      1


If the hazard ratio is less than 1, then the predictor is protective (i.e., associated with improved survival) and if the hazard ratio is greater than 1, then the predictor is associated with increased risk (or decreased survival).