

A convolutional neural network model for survival prediction based on prognosis-related cascaded Wx feature selection

https://www.laboratoryinvestigation.org/article/S0023-6837(22)00114-3/fulltext

https://github.com/wangwangCCChen/CNN-Cox

https://github.com/ucsffrancislab/CNN-Cox

In [1]:
#from Trainmodel import traindcnncoxmodel,traincnncoxmodel
#from utils import avgcindex

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1" 
import math
import numpy as np
import pandas as pd
#from model import cnncox,dcnncox,nncox
from earlystoping import MyCallback
from utils import nll,avgcindex,setup_seed
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold,train_test_split
from lifelines.utils import concordance_index
import matplotlib.pyplot as plt
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense,Dropout,Input,Flatten,concatenate
from tensorflow.keras.regularizers import l2

2024-04-18 17:22:20.340972: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


GENE_2_counts_normalized.subject_unique.metadata.all.tsv

was created from the REdiscoverTE output converted to a tsv.

The metadata came from Eduardo's initial gbm_train/gbm_test data files.

In [3]:

cancer_name='TCGA'
Cindex=[]

current_path='../data/our/'
output_path=current_path+'/GENE_2_counts_normalized.subject_unique.metadata.all.tsv'
save_path="../save model/our/my2DCNNCox/"
os.makedirs(save_path,exist_ok=True)

In [4]:

seed=42

setup_seed(seed)

df_exp=pd.read_csv(output_path,index_col=0,sep="\t",low_memory=False)

In [5]:
df_exp.head()

,sex,IDH,x1p19q,TERT,MGMT,Age,Survival_months,Vital_status,EGFR_re,CDKN2A_re,...,ENSG00000284649,ENSG00000284671,ENSG00000284680,ENSG00000284684,ENSG00000284691,ENSG00000284701,ENSG00000284723,"ENSG00000284733,ENSG00000284662",ENSG00000284741,NA
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,male,WT,non-codel,NaN,Unmethylated,78,14.718995,1,Wildtype,Deleted,...,7.766,9.993,0,0.0,47.574,0,1,0.0,0.0,569.221
02-0055,female,WT,non-codel,NaN,Unmethylated,62,2.496972,1,Amplified,Wildtype,...,10.742,0.000,0,0.0,25.980,0,0,0.0,0.0,491.114
02-2485,male,WT,non-codel,Mutant,Unmethylated,53,15.441803,0,Amplified,Wildtype,...,5.379,0.000,0,0.0,69.000,0,1,0.0,0.0,717.150
02-2486,male,WT,non-codel,NaN,Unmethylated,64,16.197466,0,Amplified,Deleted,...,2.037,4.746,0,0.0,49.948,0,0,0.0,0.0,274.183
06-0125,female,WT,non-codel,Mutant,Methylated,63,47.573895,1,Amplified,Deleted,...,8.879,4.237,0,0.0,122.020,0,1,4.0,0.0,657.634

In [6]:
df_exp.drop(columns=['IDH','x1p19q','TERT','MGMT'],inplace=True)
df_exp.head()


# EGFR_re, CDKN2A_re ?

# what is the column "NA" from?

,sex,Age,Survival_months,Vital_status,EGFR_re,CDKN2A_re,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,...,ENSG00000284649,ENSG00000284671,ENSG00000284680,ENSG00000284684,ENSG00000284691,ENSG00000284701,ENSG00000284723,"ENSG00000284733,ENSG00000284662",ENSG00000284741,NA
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,male,78,14.718995,1,Wildtype,Deleted,2350.460,1.000,633.000,439.035,...,7.766,9.993,0,0.0,47.574,0,1,0.0,0.0,569.221
02-0055,female,62,2.496972,1,Amplified,Wildtype,2893.011,825.001,2382.838,569.035,...,10.742,0.000,0,0.0,25.980,0,0,0.0,0.0,491.114
02-2485,male,53,15.441803,0,Amplified,Wildtype,4940.435,5.000,1128.869,695.463,...,5.379,0.000,0,0.0,69.000,0,1,0.0,0.0,717.150
02-2486,male,64,16.197466,0,Amplified,Deleted,4338.707,7.000,1089.000,588.688,...,2.037,4.746,0,0.0,49.948,0,0,0.0,0.0,274.183
06-0125,female,63,47.573895,1,Amplified,Deleted,3621.526,6.000,1226.225,632.096,...,8.879,4.237,0,0.0,122.020,0,1,4.0,0.0,657.634

In [7]:
#df_exp.fillna(0,inplace=True)

if 'sex' in df_exp.columns:
    df_exp['sex'].replace(to_replace={'female':0, 'male':1}, inplace=True)
if 'MGMT' in df_exp.columns:
    df_exp['MGMT'].replace(to_replace={'Unmethylated':0, 'Methylated':1}, inplace=True)
if 'EGFR_re' in df_exp.columns:
    df_exp['EGFR_re'].replace(to_replace={"Wildtype":0, "Amplified":1}, inplace=True)
if 'CDKN2A_re' in df_exp.columns:
    df_exp['CDKN2A_re'].replace(to_replace={"Wildtype":0, "Amplified":1, "Deleted":2}, inplace=True)

df_exp.head()

,sex,Age,Survival_months,Vital_status,EGFR_re,CDKN2A_re,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,...,ENSG00000284649,ENSG00000284671,ENSG00000284680,ENSG00000284684,ENSG00000284691,ENSG00000284701,ENSG00000284723,"ENSG00000284733,ENSG00000284662",ENSG00000284741,NA
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,1,78,14.718995,1,0,2,2350.460,1.000,633.000,439.035,...,7.766,9.993,0,0.0,47.574,0,1,0.0,0.0,569.221
02-0055,0,62,2.496972,1,1,0,2893.011,825.001,2382.838,569.035,...,10.742,0.000,0,0.0,25.980,0,0,0.0,0.0,491.114
02-2485,1,53,15.441803,0,1,0,4940.435,5.000,1128.869,695.463,...,5.379,0.000,0,0.0,69.000,0,1,0.0,0.0,717.150
02-2486,1,64,16.197466,0,1,2,4338.707,7.000,1089.000,588.688,...,2.037,4.746,0,0.0,49.948,0,0,0.0,0.0,274.183
06-0125,0,63,47.573895,1,1,2,3621.526,6.000,1226.225,632.096,...,8.879,4.237,0,0.0,122.020,0,1,4.0,0.0,657.634

In [8]:
gene_exp=df_exp.dropna(axis=0,subset = ["Vital_status", "Survival_months"])
E=np.array(gene_exp.pop("Vital_status"))
Y=np.array(gene_exp.pop("Survival_months"))

In [9]:
gene_exp.head()

,sex,Age,EGFR_re,CDKN2A_re,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,...,ENSG00000284649,ENSG00000284671,ENSG00000284680,ENSG00000284684,ENSG00000284691,ENSG00000284701,ENSG00000284723,"ENSG00000284733,ENSG00000284662",ENSG00000284741,NA
IID,,,,,,,,,,,,,,,,,,,,,
02-0047,1,78,0,2,2350.460,1.000,633.000,439.035,304.000,534.288,...,7.766,9.993,0,0.0,47.574,0,1,0.0,0.0,569.221
02-0055,0,62,1,0,2893.011,825.001,2382.838,569.035,497.997,1123.424,...,10.742,0.000,0,0.0,25.980,0,0,0.0,0.0,491.114
02-2485,1,53,1,0,4940.435,5.000,1128.869,695.463,743.572,503.997,...,5.379,0.000,0,0.0,69.000,0,1,0.0,0.0,717.150
02-2486,1,64,1,2,4338.707,7.000,1089.000,588.688,276.264,827.419,...,2.037,4.746,0,0.0,49.948,0,0,0.0,0.0,274.183
06-0125,0,63,1,2,3621.526,6.000,1226.225,632.096,602.204,250.999,...,8.879,4.237,0,0.0,122.020,0,1,4.0,0.0,657.634

In [10]:
E.shape

(118,)

In [11]:
E

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1])


Vital_status=1 is deceased. Meaning a vital status of 0 is censored.

Not sure if that is what the algorithm is expecting.

In [12]:
# change 0's to 1's and 1's to 0's
E = np.where((E==0)|(E==1), E^1, E)

In [13]:
E

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
Y.shape

(118,)

In [15]:
Y[0:15]

array([14.7189952,  2.4969724, 15.441803 , 16.1974657, 47.5738952,
       12.9448306, 11.8934738, 10.2835837,  7.1623682,  5.4210585,
       13.6019286,  1.0842117, 12.484862 ,  4.928235 ,  9.2650818])

In [16]:
len(gene_exp.columns)

55666

In [17]:
math.ceil(len(gene_exp.columns)**0.5)

236

In [18]:
math.ceil(len(gene_exp.columns)**0.5)**2

55696


Add a number of columns to make the dataframe column count a square ( 236 x 236 = 55696 )

In [19]:
#for i in range(55696-len(gene_exp.columns)):
#    print("extra"+str(i), end=", ")
#    col=str("extra"+str(i))
#    gene_exp["extra"+str(i)]=0

extra=["extra"+str(i) for i in range( (math.ceil(len(gene_exp.columns)**0.5)**2) - len(gene_exp.columns) )]
#gene_exp[extra]=0

gene_exp=pd.concat([gene_exp, pd.DataFrame(columns = extra)]).fillna(0)

#gene_exp.assign(extra=0)
#gene_exp.insert(2, "expenditure", 4500, allow_duplicates=False)

In [20]:
gene_exp.columns

Index(['sex', 'Age', 'EGFR_re', 'CDKN2A_re', 'ENSG00000000003',
       'ENSG00000000005', 'ENSG00000000419', 'ENSG00000000457',
       'ENSG00000000460', 'ENSG00000000938',
       ...
       'extra20', 'extra21', 'extra22', 'extra23', 'extra24', 'extra25',
       'extra26', 'extra27', 'extra28', 'extra29'],
      dtype='object', length=55696)

In [21]:
len(gene_exp.columns)

55696

In [22]:
X=np.array(gene_exp)

In [23]:
X.shape

(118, 55696)

In [24]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [25]:
X=X.astype('float64')

In [26]:
X.shape

(118, 55696)

In [27]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [28]:
# Remove the first two columns (OS and OS.time)
#X=X[:,2:]

In [29]:
X.shape

(118, 55696)

In [30]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [31]:
scaler=StandardScaler().fit(X)

In [32]:
X[0:4,0:4]

array([[ 1., 78.,  0.,  2.],
       [ 0., 62.,  1.,  0.],
       [ 1., 53.,  1.,  0.],
       [ 1., 64.,  1.,  2.]])

In [33]:
X=scaler.transform(X)

In [34]:
X[0:4,0:4]

array([[ 0.81361651,  1.22306379, -3.48010217,  0.50589175],
       [-1.22908027, -0.02108731,  0.28734789, -2.08955288],
       [ 0.81361651, -0.7209223 ,  0.28734789, -2.08955288],
       [ 0.81361651,  0.13443158,  0.28734789,  0.50589175]])

In [35]:
X.shape

(118, 55696)

In [36]:
math.ceil(len(gene_exp.columns)**0.5)

236

In [37]:
score_tst_list = []
score_dev_list = []

#le, wi = 20, 5

# 236x236 is 55696

#le, wi = 10, 10
#le, wi = 236, 236
le, wi = math.ceil(len(gene_exp.columns)**0.5), math.ceil(len(gene_exp.columns)**0.5)

conv1_size=(1, wi)
conv2_size=(wi, 1)
input_shape = (le, wi, 1)

# using just 1 loop for now
for i in range(0,2):
        print("Range ")
        ci_tst_list = []
        ci_dev_list = []
        kf = StratifiedKFold(n_splits=5,random_state=1,shuffle=True)
        fold = 0
        for trn_index, tst_index in kf.split(X,E):
            print("Index ")
            fold +=1
            x_tst=X[tst_index]
            c_tst=E[tst_index]
            s_tst=Y[tst_index]

            x_trn, x_dev ,c_trn, c_dev , s_trn, s_dev=train_test_split(
                X[trn_index],E[trn_index],Y[trn_index],test_size=0.1,
                stratify=E[trn_index],random_state=1)

            sort_idx = np.argsort(s_trn)[::-1]
            x_trn = x_trn[sort_idx]
            s_trn = s_trn[sort_idx]
            c_trn = c_trn[sort_idx]

            x_trn = np.reshape(x_trn, (-1, le, wi))
            x_dev = np.reshape(x_dev, (-1, le, wi))
            x_tst = np.reshape(x_tst, (-1, le, wi))

            x_trn = x_trn.reshape(x_trn.shape[0], le, wi, 1)
            x_dev = x_dev.reshape(x_dev.shape[0], le, wi, 1)
            x_tst = x_tst.reshape(x_tst.shape[0], le, wi, 1)
        
            #fit
            data = (x_trn, c_trn, s_trn, x_dev, c_dev, s_dev)
            modelpath = save_path+"%s_fold_%s_repeat_%s_%s.hdf5" % (
                cancer_name,fold,i+1,le*wi)
            checkpoint = MyCallback(modelpath, data)
            
            
            

            
            
            conv1=128
            #conv2=8
            conv2=128
            #dense=32
            dense=64
            input_img = Input(input_shape)
            tower_1 = Conv2D(conv1, conv1_size, activation='relu')(input_img)
            tower_1 = MaxPooling2D(1, 2)(tower_1)
            tower_1 = Flatten()(tower_1)
            tower_2 = Conv2D(conv2, conv2_size, activation='relu')(input_img)
            tower_2 = MaxPooling2D(1, 2)(tower_2)
            tower_2 = Flatten()(tower_2)
            output = concatenate([tower_1, tower_2], axis=1)
            out1 = Dense(dense, activation='relu')(output)
            last_layer = Dense(1, kernel_initializer='zeros', bias_initializer='zeros')(out1)
            model = Model(inputs=[input_img], outputs=last_layer)
            
            
            #conv1=128
            #dense=128
            #input_img = Input(input_shape)
            #tower = Conv2D(conv1, conv1_size, activation='relu')(input_img)
            #tower1 = MaxPooling2D(1, 2)(tower)
            #tower2 = Flatten()(tower1)
            #out = Dense(dense, activation='relu')(tower2)
            #last_layer = Dense(1, kernel_initializer='zeros', bias_initializer='zeros')(out)
            #model = Model(inputs=[input_img], outputs=last_layer)


            #loss
            #def nll(E, NUM_E):
            #    def loss(y_true, y_pred):
            #        hazard_ratio = tf.squeeze(tf.exp(y_pred))
            #        log_risk = tf.math.log(tf.math.cumsum(hazard_ratio))
            #        uncensored_likelihood = tf.subtract(tf.squeeze(y_pred),log_risk)
            #        censored_likelihood = uncensored_likelihood * E
            #        neg_likelihood = -tf.reduce_sum(censored_likelihood) / NUM_E
            #        return neg_likelihood
            #    return loss            
            
            model.compile(loss=[nll(c_trn, np.sum(c_trn))],optimizer="adam")
            #print(model.summary())
            
            
            print('Training...')
            history = model.fit(x_trn, s_trn, batch_size=len(x_trn),
                                epochs=100,verbose=0,callbacks=[checkpoint], shuffle=False)
            model.load_weights(modelpath)
        
            hr_pred=model.predict(x_dev,batch_size=1, verbose=1)
            hr_pred=np.exp(hr_pred)
            #print(hr_pred, c_dev, s_dev)
            print(pd.DataFrame({ 
                'hr_pred': [item for row in hr_pred for item in row], 's_dev': s_dev, 'c_dev': c_dev }))

            
            #fig,ax = plt.subplots(1)
            #ax.scatter(hr_pred,s_dev)
            ##log_pred = [-np.log(p) for p in hr_pred]
            ##ax.scatter(hr_pred,log_pred)
            #plt.title("2D - hr_pred vs s_dev")
            #plt.show()
            
            ci_dev=concordance_index(s_dev,-hr_pred,c_dev)
            
            hr_pred2=model.predict(x_tst,batch_size=1, verbose=1)
            hr_pred2=np.exp(hr_pred2)
            #print(hr_pred2, c_tst, s_tst)
            
            print(pd.DataFrame({ 
                'hr_pred2': [item for row in hr_pred2 for item in row], 's_tst': s_tst, 'c_tst': c_tst }))
            
            #fig,ax = plt.subplots(1)
            #ax.scatter(hr_pred2,s_tst)
            #plt.title("2D - hr_pred2 vs s_tst")
            #plt.show()
            
            ci_tst=concordance_index(s_tst,-hr_pred2,c_tst)
            
            ci_dev_list.append(ci_dev)
            ci_tst_list.append(ci_tst)
            
        score_dev_list.append(ci_dev_list)
        score_tst_list.append(ci_tst_list)
        

print()
print(score_dev_list)
print(score_tst_list)

Range
Index
Training...
Early stopping at 21
[Best:on_train_end]

=========================== [Best cindex (epoch = 0)] cindex=0.500000 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.000051  12.484862      0
1  0.999759  14.850415      1
2  0.999224   4.928235      0
3  0.999537   1.215631      1
4  0.999230   9.659341      1
5  0.999362   4.533976      0
6  0.999194   3.548329      0
7  0.998188   4.074008      0
8  0.999318   0.427114      1
9  0.999322  14.029042      0
24/24 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   0.999108   4.369702      0
1   0.999104   8.345145      0
2   0.998896   8.542274      1
3   0.999197   4.566831      1
4   0.998288   4.698251      1
5   0.999253   1.872729      0
6   0.999166  17.840211      0
7   0.998717   7.162368      1
8   0.999445   4.632541      0
9   0.999482   4.862525      0
10  0.999387   6.768109      1
11  0.998652   3.975443      0
12  0.998852   5.486768      1
13  0.999540  16.591725      0
14  0.999450  10.382148      1
15  0.999012  15.770352      0
16  0.999074  14.916125      0
17  0.999498  15.573223      1
18  0.999413   1.182776      0
19  0.999464   0.197129      0
20  0.998961   4.796815      0
21  0.999088   3.646894      0
22  0.999624   9.166517      0
23  0.999254   6.275286      0
Index
Training...
Early stopping at 37
[Best:on_train_end]

=========================== [Best cindex (epoch = 16)] cindex=0.450000 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  0.117487   4.369702      0
1  1.287661   6.768109      1
2  0.842386  11.729199      0
3  0.342067   1.215631      1
4  0.007674   7.162368      1
5  0.079446   4.533976      0
6  0.167460   8.345145      0
7  0.971245   3.975443      0
8  4.914492   8.542274      1
9  2.122773  16.066046      0
24/24 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   4.573551  14.718995      0
1   3.242709  47.573895      0
2   0.259553   5.421059      1
3   1.460512   2.825521      1
4   1.604695   8.969388      1
5   1.186976   2.726957      0
6   0.045410   2.562682      0
7   0.858235  28.912312      0
8   0.969223  21.881363      0
9   9.260599  25.363983      0
10  0.226514   9.396501      1
11  0.043884   9.856470      0
12  0.129683  21.289975      0
13  0.016186   2.858376      0
14  0.391966   1.215631      1
15  0.588689  11.269231      0
16  3.661703  11.006391      0
17  0.657133  13.634783      1
18  0.404111  15.934627      0
19  0.128960   8.837968      0
20  1.974922   8.870823      1
21  0.485621   5.421059      1
22  0.087005  13.339089      0
23  2.010417   4.533976      0
Index
Training...
Early stopping at 21
[Best:on_train_end]

=========================== [Best cindex (epoch = 0)] cindex=0.333333 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.000462  11.729199      0
1  0.999963   1.215631      1
2  1.000278   4.533976      0
3  1.001107  10.382148      1
4  1.002729   8.542274      1
5  1.001886   4.369702      0
6  1.001902  13.601929      0
7  1.000394   2.529827      0
8  1.001503   9.856470      0
9  1.000487   2.726957      0
24/24 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   1.001343   2.496972      0
1   1.000403  16.197466      1
2   1.000314   7.162368      1
3   1.000592  12.484862      0
4   1.000686   9.265082      1
5   1.000933   3.548329      0
6   0.999689   3.745459      0
7   1.000811   6.143866      1
8   1.002261   3.121215      0
9   1.000791   3.219780      0
10  1.001100   0.952792      0
11  1.000155  11.236376      0
12  1.000908   5.388204      0
13  1.000498   7.622337      0
14  1.001377   3.909733      0
15  1.002176   9.659341      1
16  1.000518  14.850415      1
17  1.000579   1.577035      1
18  1.001455  40.510092      0
19  1.001607  16.066046      0
20  1.000700   5.158219      0
21  1.000525  10.480713      1
22  1.001143  11.532070      1
23  1.001736  20.534312      0
Index
Training...
Early stopping at 42
[Best:on_train_end]

=========================== [Best cindex (epoch = 21)] cindex=1.000000 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  0.006611   9.856470      0
1  0.181580   2.726957      0
2  0.184678   1.215631      1
3  0.033265   1.872729      0
4  0.010458   4.533976      0
5  0.041588  16.197466      1
6  0.064713   9.396501      1
7  0.075775   4.369702      0
8  0.010789   2.529827      0
9  0.084937   3.121215      0
23/23 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   0.034217  15.441803      1
1   0.204187  11.893474      0
2   0.047893  10.283584      0
3   0.047394  13.601929      0
4   0.007941   1.084212      0
5   0.104799   4.928235      0
6   0.712775   5.946737      1
7   0.000421   0.427114      1
8   0.002403  11.729199      0
9   0.028035   8.805113      1
10  0.002656   2.234133      0
11  0.042811  17.478807      0
12  0.259255  29.010877      0
13  0.017381   4.074008      0
14  0.016098   5.421059      1
15  0.029801   5.059655      0
16  0.031895  14.029042      0
17  0.000051   7.589482      0
18  0.132588   7.293788      1
19  0.016139   2.529827      1
20  0.121717  15.376093      0
21  0.037710  11.729199      1
22  0.001432   0.854227      0
Index
Training...
Early stopping at 21
[Best:on_train_end]

=========================== [Best cindex (epoch = 0)] cindex=0.857143 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.000892   9.856470      0
1  1.001132   4.369702      0
2  1.001354   9.396501      1
3  1.001599   3.548329      0
4  1.000552   4.928235      0
5  1.001090  15.441803      1
6  1.001700   9.659341      1
7  1.001285  13.601929      0
8  1.001513   2.858376      0
9  1.002061   8.345145      0
23/23 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   1.001376  12.944831      0
1   1.000862   8.509419      1
2   1.001601   6.800964      1
3   1.000842   4.533976      0
4   1.001587  10.612133      0
5   1.001155  10.940682      0
6   1.000833  34.891904      0
7   1.001031  14.521866      0
8   1.001216  14.916125      0
9   1.001005  13.766203      0
10  1.001277  15.934627      0
11  1.001551   0.164274      0
12  1.000564   8.870823      0
13  1.000816   1.215631      1
14  1.001483   2.529827      0
15  1.001011   4.763960      1
16  1.001217   5.256784      1
17  1.001449   9.790760      1
18  1.001245   4.665396      0
19  1.000399   7.359498      1
20  1.001720   6.045302      1
21  1.001210   3.088361      0
22  1.000206   5.913882      0
Range
Index
Training...
Early stopping at 21
[Best:on_train_end]

=========================== [Best cindex (epoch = 0)] cindex=0.600000 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.000450  12.484862      0
1  0.998633  14.850415      1
2  0.999632   4.928235      0
3  0.999484   1.215631      1
4  0.999824   9.659341      1
5  0.999837   4.533976      0
6  0.999238   3.548329      0
7  0.999198   4.074008      0
8  1.000226   0.427114      1
9  0.999889  14.029042      0
24/24 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   1.000297   4.369702      0
1   0.999891   8.345145      0
2   0.999935   8.542274      1
3   0.999095   4.566831      1
4   0.999671   4.698251      1
5   0.999491   1.872729      0
6   0.999766  17.840211      0
7   0.999755   7.162368      1
8   0.999149   4.632541      0
9   1.000018   4.862525      0
10  0.999355   6.768109      1
11  0.999895   3.975443      0
12  0.999219   5.486768      1
13  0.999475  16.591725      0
14  0.999873  10.382148      1
15  1.000237  15.770352      0
16  0.999693  14.916125      0
17  0.999550  15.573223      1
18  0.999930   1.182776      0
19  0.999613   0.197129      0
20  0.999855   4.796815      0
21  0.999155   3.646894      0
22  0.999681   9.166517      0
23  0.999590   6.275286      0
Index

Training...
Early stopping at 42
[Best:on_train_end]

=========================== [Best cindex (epoch = 21)] cindex=0.450000 ==================================
10/10 [==============================] - 0s 2ms/step
       hr_pred      s_dev  c_dev
0     1.551658   4.369702      0
1    43.735863   6.768109      1
2    14.604047  11.729199      0
3     3.263143   1.215631      1
4     0.005578   7.162368      1
5     0.161163   4.533976      0
6    16.055540   8.345145      0
7   325.362152   3.975443      0
8  1085.299316   8.542274      1
9    42.942074  16.066046      0
24/24 [==============================] - 0s 2ms/step
       hr_pred2      s_tst  c_tst
0    320.461151  14.718995      0
1    162.558090  47.573895      0
2      2.252332   5.421059      1
3     59.848728   2.825521      1
4     68.576744   8.969388      1
5     12.680838   2.726957      0
6      0.703111   2.562682      0
7     67.946358  28.912312      0
8     17.712248  21.881363      0
9   2125.560547  25.363983      0
10     3.455887   9.396501      1
11     0.300003   9.856470      0
12     0.691172  21.289975      0
13     0.007184   2.858376      0
14     7.746673   1.215631      1
15    11.151496  11.269231      0
16   108.789825  11.006391      0
17    13.523222  13.634783      1
18    17.821085  15.934627      0
19     0.783124   8.837968      0
20   138.689240   8.870823      1
21     8.342812   5.421059      1
22     0.122684  13.339089      0
23   201.766907   4.533976      0
Index
Training...
Early stopping at 21
[Best:on_train_end]

=========================== [Best cindex (epoch = 0)] cindex=0.333333 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  1.000757  11.729199      0
1  1.000349   1.215631      1
2  1.000927   4.533976      0
3  1.001539  10.382148      1
4  1.003720   8.542274      1
5  1.002978   4.369702      0
6  1.003145  13.601929      0
7  1.001398   2.529827      0
8  1.001155   9.856470      0
9  1.000902   2.726957      0
24/24 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   1.002702   2.496972      0
1   1.000626  16.197466      1
2   1.000388   7.162368      1
3   1.000571  12.484862      0
4   1.001054   9.265082      1
5   1.000979   3.548329      0
6   1.000332   3.745459      0
7   1.001323   6.143866      1
8   1.002841   3.121215      0
9   1.001350   3.219780      0
10  1.001733   0.952792      0
11  1.000468  11.236376      0
12  1.000496   5.388204      0
13  1.000404   7.622337      0
14  1.001137   3.909733      0
15  1.001319   9.659341      1
16  1.000826  14.850415      1
17  1.000762   1.577035      1
18  1.001740  40.510092      0
19  1.001216  16.066046      0
20  1.000559   5.158219      0
21  1.001590  10.480713      1
22  1.000803  11.532070      1
23  1.001967  20.534312      0
Index
Training...
Early stopping at 37
[Best:on_train_end]

=========================== [Best cindex (epoch = 16)] cindex=0.909091 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  0.391872   9.856470      0
1  2.741884   2.726957      0
2  3.604975   1.215631      1
3  0.751838   1.872729      0
4  1.343325   4.533976      0
5  2.858708  16.197466      1
6  1.028874   9.396501      1
7  2.865706   4.369702      0
8  0.680412   2.529827      0
9  1.713594   3.121215      0
23/23 [==============================] - 0s 2ms/step
     hr_pred2      s_tst  c_tst
0    1.065201  15.441803      1
1   10.184117  11.893474      0
2    1.380485  10.283584      0
3    1.397977  13.601929      0
4    0.213357   1.084212      0
5    1.378619   4.928235      0
6    4.806723   5.946737      1
7    0.105771   0.427114      1
8    0.526483  11.729199      0
9    0.873542   8.805113      1
10   0.431165   2.234133      0
11   3.644696  17.478807      0
12   3.451077  29.010877      0
13   0.508461   4.074008      0
14   0.502975   5.421059      1
15   0.808333   5.059655      0
16   1.765570  14.029042      0
17   0.111054   7.589482      0
18   3.998679   7.293788      1
19   0.830163   2.529827      1
20   1.580815  15.376093      0
21   3.835764  11.729199      1
22   0.153082   0.854227      0
Index
Training...
Early stopping at 33
[Best:on_train_end]

=========================== [Best cindex (epoch = 12)] cindex=0.571429 ==================================
10/10 [==============================] - 0s 2ms/step
    hr_pred      s_dev  c_dev
0  0.600645   9.856470      0
1  1.915052   4.369702      0
2  0.881180   9.396501      1
3  1.079846   3.548329      0
4  1.234557   4.928235      0
5  3.097939  15.441803      1
6  2.107882   9.659341      1
7  0.765387  13.601929      0
8  0.963124   2.858376      0
9  1.767285   8.345145      0
23/23 [==============================] - 0s 2ms/step
    hr_pred2      s_tst  c_tst
0   1.156994  12.944831      0
1   2.564577   8.509419      1
2   1.769809   6.800964      1
3   1.166600   4.533976      0
4   4.137121  10.612133      0
5   0.886079  10.940682      0
6   0.810981  34.891904      0
7   0.960493  14.521866      0
8   1.163941  14.916125      0
9   1.070414  13.766203      0
10  1.761690  15.934627      0
11  0.191563   0.164274      0
12  0.545569   8.870823      0
13  1.079591   1.215631      1
14  1.020168   2.529827      0
15  1.694827   4.763960      1
16  1.136373   5.256784      1
17  1.220047   9.790760      1
18  1.022631   4.665396      0
19  1.330473   7.359498      1
20  1.154550   6.045302      1
21  2.155396   3.088361      0
22  1.323058   5.913882      0

[[0.5, 0.45, 0.3333333333333333, 1.0, 0.8571428571428571], [0.6, 0.45, 0.3333333333333333, 0.9090909090909091, 0.5714285714285714]]
[[0.2692307692307692, 0.4628099173553719, 0.43023255813953487, 0.3333333333333333, 0.49056603773584906], [0.2564102564102564, 0.4380165289256198, 0.4418604651162791, 0.37373737373737376, 0.5849056603773585]]


If the hazard ratio is less than 1, then the predictor is protective (i.e., associated with improved survival) and if the hazard ratio is greater than 1, then the predictor is associated with increased risk (or decreased survival).